/lslidar_driver_node:
  ros__parameters: 
    frame_id: lidar_link
    group_ip: 224.1.1.2
    add_multicast: false 
    device_ip: 192.168.1.200
    device_ip_difop: 192.168.1.102
    msop_port: 2368
    difop_port: 2369
    lidar_name: M10_P
    angle_disable_min: 0.0
    angle_disable_max: 0.0
    min_range: 0.3
    max_range: 100.0
    use_gps_ts: false
    scan_topic: /scan
    interface_selection: serial
    serial_port_: /dev/ttyACM0
    high_reflection: false
    compensation: true
    pubScan: true
    pubPointCloud2: false
    pointcloud_topic: /lidar_points
